spring:
  application:
    name: gateway
  config:
    import: configtree:/workspace/secrets/*/
  cloud:
    bootstrap:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/book/**
          filters:
            - RewritePath=/book/(?<path>.*), /$\{path}
        - id: erp
          uri: http://erp:8080
          predicates:
            - Path=/erp/**
          filters:
            - RewritePath=/erp/(?<path>.*), /$\{path}            
  keycloak:
      server-url: http://keycloak-server:8080

  redis:
    connect-timeout: 2s
    host: gateway-redis
    port: 6379
    timeout: 1s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: book:gateway
  security:
    oauth2: 
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.greeta.net/realms/book-realm
          jwk-set-uri: ${spring.keycloak.server-url}/realms/book-realm/protocol/openid-connect/certs
       

jwt:
  auth:
    converter:
      resource-id: book-app
      principal-attribute: preferred_username

book-app:
  base-url: https://book.greeta.net
  redirect-url: ${book-app.base-url}/*

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


server.forward-headers-strategy: framework

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    groups-order: ASC
    path: /
    config-url: /v3/api-docs/swagger-config
    urls:
      # - url: /v3/api-docs
      #   name: API Gateway Service
      #   primaryName: API Gateway Service
      - url: /book/v3/api-docs
        name: Book Service
      - url: /erp/v3/api-docs
        name: ERP Service